### ISSUE TITLE
Can't receive video streaming from WAN

### ISSUE THREAD

**Issue by rikiata** [Lakemast/WifiCar#1]
Sir,I cant receive espcam32 mqtt image on app.How to cofigure the code or app to receive live video in app?

**Comment by Lakemast** [comment]
Hi Friend,

First your smartphone needs to be connected to same WiFi network of your ESP32.
Second you need to change to your **ESP32 IP** the field **Camera URL**  in the APP **Settings**:

- http://**<your_ESP32_IP>**:81/stream
(_replace **<your_ESP32_IP>** with your **ESP32 IP**_)


To do that you need to know what is your **ESP32 IP**. 

If you know your **ESP32 IP**  run this small test to ensure your ESP32 is running:
- Open your browser and type your **ESP32 IP** in your web browser
- Something like this image will show
    
![ESP32-test](https://user-images.githubusercontent.com/25143692/213866618-14574dd0-f594-414e-997f-b4ae039d283e.JPG)

Notice that my **ESP32 IP** is  **192.168.15.41** in my LAN (Local Area Network). Now click on _START STREAM_ and some like below the video stream should be shown in your browser.

![video-stream-esp32](https://user-images.githubusercontent.com/25143692/213867023-78d7da9b-36da-4205-8321-a441ba3a6502.JPG)

If none of that works please let me know what is your Android Version and how you are powering ESP32.

**Comment by rikiata** [comment]
Friend,I can access live video on browser(phone or laptop on same wifi.I have changed camera url- http://192.168.1.102:81/stream
but I cant stream video on app screen through mqtt(anywhere in the world).But I can control servo and the motors,Please help.

**Comment by Lakemast** [comment]
What is your Android Version ?

Could you please attach a image from app home and settings screen?

**Comment by Lakemast** [comment]
Did you install the app through .apk or through Android Studio ?

**Comment by rikiata** [comment]
![wificar](https://user-images.githubusercontent.com/86194439/213869347-4c9960b7-4a05-41d6-89ba-0274441262b4.jpg)

ANDROID 10 VERSION

**Comment by rikiata** [comment]
I installed the app through apk

**Comment by rikiata** [comment]
![Screenshot_2023-01-21-19-10-20-629_com example wificar](https://user-images.githubusercontent.com/86194439/213869583-1db5d9d9-7759-4f94-bad2-9cec2bb9fc10.jpg)

**Comment by Lakemast** [comment]
Hi Friend,

I updated the app. Try to install this new uploaded apk [WiFiCar-fixed.apk](https://github.com/Lakemast/WifiCar/blob/master/WiFiCarMQTT/WiFiCar-fixed.apk)

Tell me if it worked.

**Comment by rikiata** [comment]
It's working on local wifi. But when I try to connect(4g mobile)  with mqtt, I can control motor,servo and espcam led from anywhere. But can't monitor live video on app.

**Comment by rikiata** [comment]
I want to control the car from anywhere in the world through mqtt with live video streaming. 

Is it possible?

**Comment by Lakemast** [comment]
I got it.

As far as I know MQTT is not a protocol for streaming video.  The only workaround that I know is you make your ESP32 IP static on your Router and use Port Routing and DDNS to access your video stream.

That's why I wrote a disclaimer on project description saying that WAN will require some workaround.

On your Router, you will need to reserve an IP address to ESP32

So you will need sign up at a DDNS provider like  NOIP and register a Domain (_Example: wificar.ddns.net_) and turn up DDNS feature on Router and log in.

After that you need to assign this domain to your  gateway and then port forward to ESP 32 IP and port 81.

I know some chinese cameras app do that without all this workaround, but I didn't find out yet how to do it.

**Comment by Lakemast** [comment]
If you do this workaround it is possible that video streaming delay will be huge.

**Comment by Lakemast** [comment]
Sorry I forgot to say after you do all I said, you will need to change in the App the camera URL with your domain _Example: http://wificar.ddns.net/_

**Comment by rikiata** [comment]
Did you test the esp32cam on ddns?worked? 
Can I use raspberri pi camera url(internet streaming) on your app? If possible, I can control the motors and servo through matt and video streaming through raspberri pi camera. 

Or. Can I use v380 camera with your app? 

Please suggest.

**Comment by rikiata** [comment]
I watched your YouTube video. Video streaming is ddns based or wifi based?

**Comment by Lakemast** [comment]
> Did you test the esp32cam on ddns?worked? 
> Can I use raspberri pi camera url(internet streaming) on your app? If possible, I can control the motors and servo through matt and video streaming through raspberri pi camera. 
> 
> Or. Can I use v380 camera with your app? 
> 
> Please suggest. 

Yes I've tested esp32 cam using ddns. It worked but not as expected. The video delay was huge.

Yes, if your camera url is a MJPEG stream you can use my app with raspberry pi camera or any MJPEG camera.

My app used this other repository to stream video
[perthcpe23/android-mjpeg-view](https://github.com/perthcpe23/android-mjpeg-view)

**Comment by rikiata** [comment]
Can you suggest any readymade mjpeg camera?

**Comment by Lakemast** [comment]
> I watched your YouTube video. Video streaming is ddns based or wifi based? 

None of them.

DDNS stands for Dynamic Domain Name System and is used to translate IP to domains
_example: 142.251.132.238 to google.com_

WiFi is a wireless networking technology that uses radio waves to provide wireless high-speed Internet access. So WiFi basically connects your devices like phone, pc to the router.

Video streaming can be based on several protocols like : RTSP, ONVIF, MJPEG over HTTP and many others.

**Comment by Lakemast** [comment]
> Can you suggest any readymade mjpeg camera? 

Sorry, but I've worked only with theses modular cameras like esp32cam or raspberry pi cameras.

**Comment by rikiata** [comment]
Thanks for your valuable ideas. I will try to make
Mjpeg based raspberri pi internet camera. Then I can control the car from anywhere with live video streaming.

**Comment by Lakemast** [comment]
> Thanks for your valuable ideas. I will try to make
> Mjpeg based raspberri pi internet camera. Then I can control the car from anywhere with live video streaming. 

You are welcome! Maybe you can find some repository in github to help with at.
